name: Deploy Lambda to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 psycopg2-binary

      - name: Package Lambda function
        run: |
          zip -r lambda_package.zip lambda_function.py requirements.txt

      - name: Upload CSVs to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 cp authors.csv s3://amkadian-cf-templates--1obv518dn0xj-us-east-1/authors.csv
          aws s3 cp books.csv s3://amkadian-cf-templates--1obv518dn0xj-us-east-1/books.csv

      - name: Update Lambda function code
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws lambda update-function-code --function-name myTestFunction --zip-file fileb://lambda_package.zip
